name: internal-linking
channels:
  - conda-forge
dependencies:
  - python=3.8
  - openpyxl==3.0.5
  - pandas==1.1.5
  - requests==2.25.1
  - spacy==2.3.5
  - jupyterlab==2.2.9
  - pip:
      - bs4==0.0.1
      - lxml==4.6.2
